# Generated by Django 4.2.3 on 2023-09-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='hours_worked',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='overtime',
            name='overtime_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=5),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='regular_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
